### ISSUE TITLE
Unable to control 2014 robots

### ISSUE THREAD

**Issue by camearle20** [FRC-Utilities/LibDS-C#1]
Using the latest version of LibDS at the time of this writing, I am unable to get LibDS to control a 2014 protocol robot.  Network activity indicates that there is indeed a connection between the driver station and the robot, and LibDS indicates that comms and robot code are true, yet no commands work.  Enabling appears to have no effect, and even attempting to run methods such as DS_RebootRobot yields no result.  For reference, using the 2016 protocol with a 2016 robot works as expected.  Additionally, using the latest version of QDriverStation shows the exact same results.  The code in use is available at [https://github.com/camearle20/CartDS](https://github.com/camearle20/CartDS).  It is built to use on a Raspberry Pi, yet the same results are seen running the code on a standard 64 bit Linux machine.

**Comment by alex-spataru** [comment]
Hi,


I think that this has something to do with how LibDS generates DS-to-robot packets. I will check the implementation of the 2014 protocol for errors and notify you if I find something. Anyways, do you have access to the logs (printed on the console/stdout) generated by LibDS? They could help us to find the source of this issue.


Thanks for the report!

Alex Spataru

________________________________

**Comment by camearle20** [comment]
Thanks for the quick reply!  I'm not at our shop right now and don't have access to a robot, so I will have to run some more tests tomorrow.  From what I saw, there was no console output except for that produced by my code.  I also didn't see any log files.  Is there some place I should look/some method that enables this functionality?

Thanks again,
Cameron Earle
Team 401

**Comment by alex-spataru** [comment]
I fixed some issues with the FRC 2014 protocol implementation, and everything *should* work now. The problem was that the CRC32 checksum was not calculated correctly for the size of the generated DS-to-robot packets. Also, the version bytes sent to the robot where outdated.

After fixing these issues, the generated packets sent by the FRC DS and QDriverStation where exactly the same (at least under my test conditions).

Could you please check if your problem was fixed with the latest commit?
